name: Handle Project V2 Item Events

on:
  project_v2_item:
    types: [created, updated, deleted, moved]  # Handle all relevant project item events

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send event details to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Your Slack Webhook URL
        run: |
          # Load the event data
          EVENT_DATA='${{ toJson(github.event) }}'  # Use github.event directly

          # Extract details based on the event type
          ACTION=$(echo "$EVENT_DATA" | jq -r .action)
          ITEM_TITLE=$(echo "$EVENT_DATA" | jq -r .project_v2_item.title)

          # Create message based on the action
          if [[ "$ACTION" == "created" ]]; then
            MESSAGE="A new Project V2 item was created: '$ITEM_TITLE'."
          elif [[ "$ACTION" == "updated" ]]; then
            MESSAGE="A Project V2 item was updated: '$ITEM_TITLE'."
          elif [[ "$ACTION" == "deleted" ]]; then
            MESSAGE="A Project V2 item has been deleted: '$ITEM_TITLE'."
          elif [[ "$ACTION" == "moved" ]]; then
            MESSAGE="A Project V2 item was moved: '$ITEM_TITLE'."
          fi

          # Send message to Slack
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"GitHub Projects V2 Update", "blocks":[{"type":"section","text":{"type":"mrkdwn","text":"'"$MESSAGE"'"}}]}' \
          "$SLACK_WEBHOOK_URL"
