name: Project V2 Items to Slack

on:
  project_v2_item:
    types: [created, updated, deleted]

jobs:
  project_v2_item_to_slack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Reformat JSON and send to Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "Reformatting JSON..."
        EVENT_JSON=$(jq -n --argjson event "${{ toJson(github.event) }}" '{
          text: "Project V2 Item \($event.action): \($event.project_v2_item.title)",
          attachments: [
            {
              title: $event.project_v2_item.title,
              text: $event.project_v2_item.body,
              color: if $event.action == "created" then "good" elif $event.action == "updated" then "warning" else "danger" end
            }
          ]
        }')

        echo "Sending to Slack..."
        curl -X POST -H 'Content-type: application/json' --data "$EVENT_JSON" $SLACK_WEBHOOK_URL
